<<<<<<< HEAD
# ----------- CONFIGURABLE START -----------
title:            "LiberXue|FullStack|独立开发者|jekyll blog|GitHub blog"
description:      "Full Stack独立开发者|欢迎来到 LiberXue「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              https://liberxue.github.io # 域名
signoff:          "LiberXue" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /book
    external:     false
  - name:         旅游
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------
=======
title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog   https://bhlqh.github.io/UndeadSolaireTest/
url: "https://bhlqh.github.io/UndeadSolaireTest/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
>>>>>>> 1daf57c961fa31bc4609eab122a1628e5f6b14f7

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
